**Задание на повторение материала
    1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
   

In [3]:
import numpy as np
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
    

In [4]:
b = a.reshape(12, 1)
c = a.reshape(2, 6)
d = a.reshape(6, 2)
e = a.reshape(3, 4)
f = a.reshape(4, 3)
b

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
   

In [6]:
b1 = a.reshape(12, -1)
c1 = a.reshape(2, -1)
d1 = a.reshape(6, -1)
e1 = a.reshape(-1, 4)
f1 = a.reshape(-1, 3)


 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
   

In [25]:
b1[1][0],b1[1]
# - нет(два измерения ,по одному измерению равно 1"единица" по второму 12"единиц")
# в первом случае мы получаем число, во втором массив с одним числом

(13, array([13]))

 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
   

In [26]:
massiv = np.random.randn(3, 4)
massiv_flatten = massiv.flatten()
massiv, massiv_flatten, massiv.size == massiv_flatten.size

(array([[-0.60662596,  1.53592801,  1.59788063, -0.95884207],
        [-1.05976135,  0.10953747,  0.50566636, -0.44878013],
        [-1.73248443, -0.58340795,  0.92844122,  1.10804585]]),
 array([-0.60662596,  1.53592801,  1.59788063, -0.95884207, -1.05976135,
         0.10953747,  0.50566636, -0.44878013, -1.73248443, -0.58340795,
         0.92844122,  1.10804585]),
 True)

 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
    

In [27]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?
    

In [28]:
b = np.array([np.arange(20, 1, -2)])
b.shape, a.shape

((1, 10), (10,))

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
    

In [29]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
v = np.concatenate((a, b), axis=0)
v.size == 10, v

(True,
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]]))

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
    

In [30]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
# B_inv = np.linalg.inv(B)
B_rank = np.linalg.matrix_rank(B)
B_det = np.linalg.det(B)
B_rank, B_det
# обратную матрицу можно посчитать только для матрицы определитьель которой не равен 0

(2, 0.0)

10.  Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
    

In [31]:
np.random.seed(42)


11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
   

In [32]:
np.random.seed(42)
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.
    

In [33]:
C = c.reshape(4, -1)
D = B + C * 10
D_det = np.linalg.det(D)
D_rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
print(f'Матрица C:\n{C},\n'
      f'Матрица C * 10:\n{C*10},\n'
      f'Матрица B:\n{B},\n'
      f'Матрица D:\n{D},\n'
      f'\nОпределитель матрицы D: {D_det},\n'
      f'Ранг матрицы D: {D_rank},\n'
      f'Обратная матрица к матрице D:\n{D_inv}')

Матрица C:
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]],
Матрица C * 10:
[[ 60  30 120 140]
 [100  70 120  40]
 [ 60  90  20  60]
 [100 100  70  40]],
Матрица B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]],
Матрица D:
[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]],

Определитель матрицы D: -28511999.999999944,
Ранг матрицы D: 4,
Обратная матрица к матрице D:
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [34]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
E = np.where(D_inv, B, C)
print(f'D_inv :\n{D_inv}\n',
      f'B :\n{B}\n',
      f'C :\n{C}\n',
      f'E :\n{E}\n')

D_inv :
[[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]
 B :
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
 C :
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
 E :
[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]



In [35]:
?np.where

Docstring:
where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples
-